default_stages: [commit]

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.1.0
    hooks:
    - id: check-ast
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: trailing-whitespace
      exclude: '^.*\.snap$'

-   repo: https://github.com/jorisroovers/gitlint
    rev: v0.11.0
    hooks:
    - id: gitlint
      entry: gitlint -c title-max-length.line-length=50 --ignore B6,B7 --msg-filename
      stages: [commit-msg]

-   repo: https://github.com/pre-commit/mirrors-eslint
    rev: v5.16.0
    hooks:
    - id: eslint
      entry: eslint --fix
      files: ^.*\.(js|jsx)$
      types: [text]
      additional_dependencies:
      - eslint@5.3.0
      - babel-eslint@9.0.0
      - eslint-plugin-import@2.15.0
      - eslint-plugin-jsx-a11y@6.1.2
      - eslint-plugin-react@7.12.4
      - eslint-config-airbnb@17.1.0
      - eslint-plugin-react@7.12.4
      - eslint-plugin-cypress@2.2.1
